---
abstract: 'Fetch historical Japanese stock quotes on Yahoo! Japan Finance.'
author:
  - 'Masanori HATA <http://www.mihr.net/> (Saitama, JAPAN)'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-YahooJPN-Quote
provides:
  Finance::YahooJPN::Quote:
    file: Quote.pm
    version: '1.08'
recommends:
  IO::Socket::Socks: '0.63'
  perl: v5.20.0
requires:
  perl: v5.16.3
resources:
  license: http://dev.perl.org/licenses/
version: '1.08'
