---
abstract: 'For fetching historical stock quotes in Japan from Yahoo! Japan Finance.'
author:
  - 'Masanori HATA <http://www.mihr.net/> (Saitama, JAPAN)'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-YahooJPN-Quote
provides:
  Finance::YahooJPN::Quote:
    file: Quote.pm
    version: 1.04
recommends:
  perl: v5.18.2
requires:
  perl: v5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.04
