---
abstract: 'For fetching historical stock quotes in Japan from Yahoo! Japan Finance.'
author:
  - 'Masanori HATA <http://www.mihr.net> (Saitama, JAPAN)'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-YahooJPN-Quote
provides:
  Finance::YahooJPN::Quote:
    file: Quote.pm
    version: 1.03
recommends:
  perl: v5.14.2
requires:
  perl: v5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
